### ISSUE TITLE
Difference between this and 2.5?

### ISSUE THREAD

**Issue by HimoriK** [samboy/nexuiz-tiny#4] opened 2023-05-07 04:45 UTC
Hello,

I'm interested in working on a modern nexuiz port, this repo is the most current besides the original project which has been abandoned.
If the differences between your version of 2.3 and 2.5 are small I would prefer this if it's more optimal.

Thanks.

**Comment by samboy** [comment] 2023-05-08 05:40
It’s very different from Stock Nexuiz. I have removed a lot of resources and added a couple of maps not with the old releases of stock Nexuiz. The most interesting thing for someone who wants to continue Nexuiz 2.5 without all of the Xonotic changes is probably this file: https://sourceforge.net/projects/nexuiz-tiny/files/Map%20graphite_b2%20Nexuiz%20Conversion/

This is a Xonotic map which I backported to Nexuiz.

**Comment by samboy** [comment] 2023-06-08 07:10
Looks like the issue is resolved. Closing.

**Closed as completed by samboy** 2023-06-08 07:10 UTC

**Comment by samboy** [comment] 2023-06-08 07:19
Also, check out Rexuiz; https://rexuiz.com
